name: Trigger auto deployment

on:
  # GitHubのActionsタブから手動で実行するためのトリガー
  workflow_dispatch:

env:
  # Azure Container Registry (ACR) のドメイン名
  CONTAINER_REGISTRY: cicd2025fn3ke44krdryu.azurecr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        # 高度なDockerビルド機能のセットアップ
        uses: docker/setup-buildx-action@v2

      - name: Set repository name to env
        # リポジトリ名（例: my-app）を抽出して環境変数に設定
        run: | 
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

      - name: Confirm if env have REPOSITORY_NAME
        # 環境変数に正しく設定されたかを確認
        run: | 
          echo ${{ env.REPOSITORY_NAME }}

      - name: Log in to container registry
        # ACRへの認証を実行（secretsに登録された資格情報を使用）
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      
      - name: Build and push container image to registry
        # Dockerイメージをビルドし、タグを付けてACRへプッシュ
        uses: docker/build-push-action@v3
        with:
          push: true
          # タグの形式: [ACRドメイン]/[リポジトリ名]:[コミットハッシュ]
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: ./
